FROM lofareosc/prefactor3-cwl

RUN groupadd -r lofaruser && \
    useradd -r -l -m -g lofaruser lofaruser

WORKDIR /home/lofaruser

RUN apt-get update && \
    apt-get install -y \
    python3-regex
RUN python3 -m pip install -Iv pyvo
#==0.9.3

RUN apt-get update && \
    apt-get install -y git

USER lofaruser
#RUN git clone https://github.com/lonbar/VLBI-cwl.git /home/lofaruser/VLBI-cwl
#RUN git clone https://github.com/rvweeren/lofar_facet_selfcal.git /home/lofaruser/LOFAR_facet-selfcal
#RUN git clone https://github.com/jurjen93/lofar_helpers /home/lofaruser/LOFAR_helpers

ENV PYTHONPATH=/home/lofaruser/VLBI-cwl/scripts/:/home/lofaruser/lofar_facet_selfcal/:$PYTHONPATH
ENV PATH=/home/lofaruser/VLBI-cwl/scripts:/home/lofaruser/lofar_facet_selfcal/:$PATH

# Install VLBI CWL
COPY . /home/lofaruser/VLBI-cwl
# Install facet-selfcal script
RUN git clone https://github.com/lmorabit/lofar_facet_selfcal.git
#RUN chmod -r +x /home/lofaruser/lofar_facet_selfcal

#RUN apt-get update && \
#    apt-get install -y git
